### ISSUE TITLE
Problem with Sinilink XY-WPCE Template

### ISSUE THREAD

**Issue by BlueWings172** [blakadder/templates#1472]
Hello

Just flashed my Sinilink XY-WPCE with Tasmota and used [this template](https://templates.blakadder.com/sinilink_XY-WPCE.html) to configure it.

I'm wondering if there is something missing in the template as when I push the power button of the computer case, it doesn't do anything. Also in Tasmota the status of the relay is always Off even when I turn it on and when I shutdown my PC from Windows , it just restarts.

It would be great if it is possible to solve any of these issues from the template.

Thanks

**Comment by diegargon** [comment]
Hello.

I purchase the USB powered version
https://templates.blakadder.com/sinilink_XY-WPCL.html

And the template is wrong, the PCE version seems similar perhaps work

The Power SW GPIO is wrong GPIO 10 is the right case in my case.

{"NAME":"XY-WPCL","GPIO":[0,0,320,0,0,224,0,32,160,0,0,0,0,0],"FLAG":0,"BASE":18, "CMND":"SO114 1 | Pulsetime 10 | SwitchMode1 2"}

The Relay must we toggle from off-on-off not lock, mine stayed on long time, and shutdown the computer again, that why i added "Pulsetime 10" (it's my first time i don't known if i doing it right but works)

For check if is powered is Switch1, a binary sensor since the button will go back to off.

In my case, the usb powered version, that binary version is related/detecte with the 'power led' signal and works but not turn off the power led of the case (i not fix that yet)

In HA i create a template for a button that read the binary sensors for show the button state

```
switch:
  - platform: template
    switches:
      camaras_salon:
        unique_id: "CamarasSalon"
        value_template: "{{ is_state('binary_sensor.switch1', 'on') }}"
        availability_template: "{{ not is_state('binary_sensor.switch1', 'unavailable') }}"
        turn_on:
          service: switch.toggle
          target:
            entity_id: switch.pcswitch_cam
        turn_off:
          service: switch.toggle
          target:
            entity_id: switch.pcswitch_cam
        icon_template: >-
          {% if is_state('binary_sensor.switch1', 'on') %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off
          {% endif %}            
```
